spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_system?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root  # Changed from 'root' for security
    password: 1234 # Use a strong password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect  # For MySQL 8.x
        generate_statistics: true
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        connection:
          provider_disables_autocommit: true
server:
  port: 8080
  servlet:
    context-path: /
socketio:
  port: 9092
  host: 0.0.0.0

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      org.hibernate.stat: DEBUG
      org.springframework.web: INFO
      org.springframework.security: WARN  # Reduce security logs
      com.zaxxer.hikari: INFO  # Connection pool monitoring