spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_system?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: true
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true

