spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      connection-test-query: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000

  ai:
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: YOUR_API_KEY
      chat:
        options:
          model: mistralai/mistral-7b-instruct:free
          headers:
            HTTP-Referer: http://localhost:8080
            X-Title: Inventory System AI
            Content-Type: application/json

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: true
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
          time_zone: UTC
        query:
          fail_on_pagination_over_collection_fetch: true
